### PR TITLE
Fix string escaping

### PR DESCRIPTION
**Pull request by antisaling**
## Description

I started by adding a gitignore as a basic chore to help me debug this, as well.

Fixed a string escape bug that was preventing us from adding certain values on the table using PSQL.
The behavior should remain unaltered for other DB backends.

I've also bumped the PSQL-12 client version.

## How Has This Been Tested?

Tested with the Python MLMD client.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
I have not experience with cpp but I reckon this introduces proper string escaping.

I also notice version bumps in bazel will likely require a different set of "snapshotted dependency cache" for which @rimolive @lampajr are more familiar.

Thank you!

**Comment by rareddy** [comment]
Any tests to verify you can add to the PR?

**Comment by antisaling** [comment]
You can create a new metadata store pointing to a Postgres DB, and then experiment with text you would usually insert for e.g. a description formatted as markdown (which is what motivated this patch).

**Review by lampajr — APPROVED** [review]
> I also notice version bumps in bazel will likely require a different set of "snapshotted dependency cache" for which @rimolive @lampajr are more familiar.

+1 once we will create the release branch we should have to re-generate the external dependencies/cache archive

The change lgtm but I'd like to test it together with https://github.com/opendatahub-io/ml-metadata/pull/1 in order to be sure that the build would work on ubi/fedora images

**Comment by lampajr** [comment]
I'd hold this PR a little bit because I'd like to setup a simple CI that performs a container build of the `Dockerfile.redhat` I added with https://github.com/opendatahub-io/ml-metadata/pull/1 - this way we can check if the UBI-based build still work with these changes

**Comment by lampajr** [comment]
> I'd hold this PR a little bit because I'd like to setup a simple CI that performs a container build of the `Dockerfile.redhat` I added with #1 - this way we can check if the UBI-based build still work with these changes

Created https://github.com/opendatahub-io/ml-metadata/pull/3 to the simple ci, this will ensure that a ubi-based image will work.

**Review by dhirajsb — APPROVED** [review]
lgtm

**Review by rimolive — APPROVED** [review]
/lgtm

I did not test the changes, but as there's no test instructions and according to Andrea's comment, you will provide an automated way to test PRs.

**Pull request merged**
